### ISSUE TITLE
Unable to launch the service getting the ERROR: Couldn't initialise service "crossbrowsertesting".

### ISSUE THREAD

**Issue by praveen-4705** [crossbrowsertesting/wdio-crossbrowsertesting-service#1]
I have installed the following command 

npm install --save-dev wdio-crossbrowsertesting-service

and given the require details

services: ['crossbrowsertesting'],
    // host: "hub.crossbrowsertesting.com",
    // port: 80,
    user: 'username',
    key: 'apikey',
    cbtTunnel: false,

but I am getting the 

ERROR: Couldn't initialise service "crossbrowsertesting".
Error: Cannot find module 'wdio-crossbrowsertesting-service'
errors

**Comment by daphnemcrossbrowser** [comment]
@praveen-4705 The service has not yet been merged into WDIO. https://github.com/webdriverio/webdriverio/pull/3959

After merging, documentation will be updated to reflect properly setting up the service for use with WDIO.

**Comment by praveen-4705** [comment]
How many days will it take to merge
