### ISSUE TITLE
Unable to run the scripts in CBT using the WebDriverIO v5

### ISSUE THREAD

**Issue by praveen-4705** [crossbrowsertesting/wdio-crossbrowsertesting-service#2]
When I try to run the tests in CBT using the WebDriverIO v5 I am following the exception

Error: A "user" or "key" was provided but could not be connected to a known cloud service (SauceLabs, Browerstack or Testingbot). Please check if given user and key properties are correct!

    services: [['crossbrowsertesting']],

    user: '',
    key: '',
    cbtTunnel: false,
    cbtTunnelOpts: {
        // any additional options from cbt_tunnels
    },

**Comment by christian-bromann** [comment]
@praveen-4705 please use the [`@wdio/crossbrowsertesting-service`](https://webdriver.io/docs/crossbrowsertesting-service.html). We moved it in-house because this one does not support v5.

**Comment by praveen-4705** [comment]
Okay
